// AUTO-RUN before next build. Reads all SVGs from public/ and writes them
// as TypeScript string constants so they're bundled at build time.
// This avoids fs.readFileSync path issues in OpenNext/Cloudflare builds.

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

const root = process.cwd();
const SVG_DIR = join(root, "public", "svg");
const OUT_FILE = join(root, "data", "svgContent.ts");

function stripSvgWrapper(raw: string): string {
  return raw
    .replace(/<\?xml[^>]*\?>\s*/gi, "")
    .replace(/<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();
}

function readInner(path: string): string {
  try {
    return stripSvgWrapper(readFileSync(path, "utf-8"));
  } catch {
    return "";
  }
}

// Cow silhouette
const cowRaw = readFileSync(join(SVG_DIR, "cow.svg"), "utf-8");
const cowInner = stripSvgWrapper(cowRaw);
const viewBoxMatch = cowRaw.match(/viewBox="([^"]*)"/);
const cowViewBox = viewBoxMatch?.[1] ?? "0 0 711.89 622.56";

// Canonical cut SVGs
const canonicalInner: Record<string, string> = {};
const canonicalDir = join(SVG_DIR, "canonical");
for (const file of readdirSync(canonicalDir)) {
  if (file.endsWith(".svg")) {
    canonicalInner[file.replace(".svg", "")] = readInner(
      join(canonicalDir, file)
    );
  }
}

// Primal region SVGs
const primalInner: Record<string, string> = {};
const primalDir = join(SVG_DIR, "primal");
for (const file of readdirSync(primalDir)) {
  if (file.endsWith(".svg")) {
    primalInner[file.replace(".svg", "")] = readInner(join(primalDir, file));
  }
}

const output = `// AUTO-GENERATED — do not edit. Regenerated by: npx tsx scripts/buildSvgData.ts
export const cowSvgInner = ${JSON.stringify(cowInner)};
export const cowViewBox = ${JSON.stringify(cowViewBox)};
export const canonicalSvgInner: Record<string, string> = ${JSON.stringify(canonicalInner, null, 2)};
export const primalSvgInner: Record<string, string> = ${JSON.stringify(primalInner, null, 2)};
`;

writeFileSync(OUT_FILE, output, "utf-8");
console.log(
  `buildSvgData: wrote ${OUT_FILE} (${Object.keys(canonicalInner).length} canonical, ${Object.keys(primalInner).length} primal)`
);
