import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: `General disclaimer for ${site.name}, operated by ${site.entity}.`,
};

export default function DisclaimerPage() {
  return (
    <div className="cut-bg">
      <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <p className="cut-content-eyebrow">
          Legal
        </p>
        <h1 className="cut-content-title font-heading">
          Disclaimer
        </h1>
        <p className="mt-2 text-sm text-[var(--text-muted)]">
          {site.entity} · Effective Date: January 1, 2026
        </p>
        <p className="mt-4 text-sm leading-relaxed text-[var(--text-muted)]">
          Aligned with the Albor Digital disclaimer framework, adapted for {site.name}{" "}
          (beef cut terminology and regional naming).
        </p>

        <div className="mt-10 space-y-8 text-[var(--text-muted)]">
          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              1. General Disclaimer
            </h2>
            <p className="mt-2 leading-relaxed">
              The products, tools, data, and content provided by {site.entity} through{" "}
              {site.name} are offered for informational and practical utility purposes
              only. While we strive for accuracy and usefulness, we make no representations
              or warranties — express or implied — regarding the completeness, accuracy,
              reliability, or suitability of any information or tool for any particular
              purpose. All use is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              2. No Professional Advice
            </h2>
            <p className="mt-2 leading-relaxed">
              Nothing provided through {site.name} constitutes legal, financial, medical,
              investment, tax, or professional advice of any kind. Any data, analysis, or
              output generated by our tools — including AI-powered features — should not
              be relied upon as a substitute for advice from a qualified professional.
              Always seek independent professional guidance before making decisions based
              on our products.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              3. AI-Generated Content
            </h2>
            <p className="mt-2 leading-relaxed">
              Where {site.name} incorporates artificial intelligence, outputs are generated
              algorithmically and may contain errors, omissions, or inaccuracies. AI
              outputs reflect patterns in training data and do not represent verified
              facts, professional opinions, or the views of {site.entity}. Users are solely
              responsible for evaluating and verifying any AI-generated content before
              acting on it.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              4. Data and Terminology
            </h2>
            <p className="mt-2 leading-relaxed">
              Regional names, cut terminology, and comparative information provided by{" "}
              {site.name} are compiled for general reference and may be incomplete,
              delayed, or subject to errors. Butchery practices, specifications, and markets
              vary. {site.entity} does not guarantee the accuracy of every source or label
              and is not responsible for decisions made based on such information.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              5. External Links
            </h2>
            <p className="mt-2 leading-relaxed">
              {site.name} may reference or link to external websites and resources.{" "}
              {site.entity} does not control and is not responsible for the content,
              accuracy, or availability of external sites. Inclusion of a link does not
              imply endorsement.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              6. Limitation of Liability
            </h2>
            <p className="mt-2 leading-relaxed">
              To the fullest extent permitted by law, {site.entity} and its owner shall
              not be liable for any direct, indirect, incidental, consequential, or
              punitive damages arising from reliance on or use of our products, tools,
              data, or content — including any errors, interruptions, or inaccuracies
              therein.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              7. Jurisdictional Notice
            </h2>
            <p className="mt-2 leading-relaxed">
              {site.name} is operated from Canada and the United States. We make no
              representation that our products are appropriate or available for use in all
              jurisdictions. Users who access {site.name} from outside these regions do
              so at their own initiative and are responsible for compliance with local laws.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-[var(--text-primary)]">
              Contact
            </h2>
            <p className="mt-2 leading-relaxed">
              <a href={`mailto:${site.email}`} className="cut-link">
                {site.email}
              </a>
            </p>
          </section>
        </div>

        <p className="mt-12 text-sm text-[var(--text-muted)]">
          <Link href="/legal/terms" className="cut-link underline">
            Terms of Service
          </Link>
          {" · "}
          <Link href="/legal/privacy" className="cut-link underline">
            Privacy Policy
          </Link>
          {" · "}
          <Link href="/legal/responsible-ai" className="cut-link underline">
            Responsible AI Policy
          </Link>
        </p>
      </main>
    </div>
  );
}
