import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: `General disclaimer for ${site.name}, operated by ${site.entity}.`,
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-full bg-gradient-to-b from-stone-50 to-amber-50/40 dark:from-stone-950 dark:to-stone-900">
      <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <p className="text-sm font-semibold uppercase tracking-widest text-amber-800 dark:text-amber-400">
          Legal
        </p>
        <h1 className="mt-3 text-4xl font-bold tracking-tight text-stone-900 dark:text-stone-50">
          Disclaimer
        </h1>
        <p className="mt-2 text-sm text-stone-600 dark:text-stone-400">
          {site.entity} · Effective Date: January 1, 2026
        </p>
        <p className="mt-4 text-sm leading-relaxed text-stone-600 dark:text-stone-400">
          Aligned with the Albor Digital disclaimer framework, adapted for {site.name}{" "}
          (beef cut terminology and regional naming).
        </p>

        <div className="mt-10 space-y-8 text-stone-700 dark:text-stone-300">
          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              1. General Disclaimer
            </h2>
            <p className="mt-2 leading-relaxed">
              The products, tools, data, and content provided by {site.entity} through{" "}
              {site.name} are offered for informational and practical utility purposes
              only. While we strive for accuracy and usefulness, we make no representations
              or warranties — express or implied — regarding the completeness, accuracy,
              reliability, or suitability of any information or tool for any particular
              purpose. All use is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              2. No Professional Advice
            </h2>
            <p className="mt-2 leading-relaxed">
              Nothing provided through {site.name} constitutes legal, financial, medical,
              investment, tax, or professional advice of any kind. Any data, analysis, or
              output generated by our tools — including AI-powered features — should not
              be relied upon as a substitute for advice from a qualified professional.
              Always seek independent professional guidance before making decisions based
              on our products.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              3. AI-Generated Content
            </h2>
            <p className="mt-2 leading-relaxed">
              Where {site.name} incorporates artificial intelligence, outputs are generated
              algorithmically and may contain errors, omissions, or inaccuracies. AI
              outputs reflect patterns in training data and do not represent verified
              facts, professional opinions, or the views of {site.entity}. Users are solely
              responsible for evaluating and verifying any AI-generated content before
              acting on it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              4. Data and Terminology
            </h2>
            <p className="mt-2 leading-relaxed">
              Regional names, cut terminology, and comparative information provided by{" "}
              {site.name} are compiled for general reference and may be incomplete,
              delayed, or subject to errors. Butchery practices, specifications, and markets
              vary. {site.entity} does not guarantee the accuracy of every source or label
              and is not responsible for decisions made based on such information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              5. External Links
            </h2>
            <p className="mt-2 leading-relaxed">
              {site.name} may reference or link to external websites and resources.{" "}
              {site.entity} does not control and is not responsible for the content,
              accuracy, or availability of external sites. Inclusion of a link does not
              imply endorsement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              6. Limitation of Liability
            </h2>
            <p className="mt-2 leading-relaxed">
              To the fullest extent permitted by law, {site.entity} and its owner shall
              not be liable for any direct, indirect, incidental, consequential, or
              punitive damages arising from reliance on or use of our products, tools,
              data, or content — including any errors, interruptions, or inaccuracies
              therein.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              7. Jurisdictional Notice
            </h2>
            <p className="mt-2 leading-relaxed">
              {site.name} is operated from Canada and the United States. We make no
              representation that our products are appropriate or available for use in all
              jurisdictions. Users who access {site.name} from outside these regions do
              so at their own initiative and are responsible for compliance with local laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
              Contact
            </h2>
            <p className="mt-2 leading-relaxed">
              <a href={`mailto:${site.email}`} className="text-amber-800 dark:text-amber-300">
                {site.email}
              </a>
            </p>
          </section>
        </div>

        <p className="mt-12 text-sm text-stone-600 dark:text-stone-400">
          <Link href="/legal/terms" className="text-amber-800 hover:underline dark:text-amber-300">
            Terms of Service
          </Link>
          {" · "}
          <Link href="/legal/privacy" className="text-amber-800 hover:underline dark:text-amber-300">
            Privacy Policy
          </Link>
          {" · "}
          <Link href="/legal/responsible-ai" className="text-amber-800 hover:underline dark:text-amber-300">
            Responsible AI Policy
          </Link>
        </p>
      </main>
    </div>
  );
}
